### ISSUE TITLE
Using libxml-ruby on heroku

### ISSUE THREAD

**Issue by ahetawal-p** [xml4r/libxml-ruby#134]
Trying to use libxml-ruby 2.9.0 on heroku and I keep on getting this error. Is there a way to use any other version fix this ?

```
/app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /app/vendor/libxml2/lib/libxml2.so: version `LIBXML2_2.9.0' not found (required by /app/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/libxml-ruby-2.9.0/libxml_ruby.so) - /app/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/libxml-ruby-2.9.0/libxml_ruby.so (LoadError)
	from /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:8:in `rescue in <top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/libxml-ruby-2.9.0/lib/libxml.rb:4:in `<top (required)>'
	from /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/libxml-ruby-2.9.0/lib/xml.rb:13:in `<top (required)>'
	from /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /app/vendor/ruby-2.2.6/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
```

**Comment by cfis** [comment]
Hmm, what's that 2.2.0-static mean in the path?

Take a look at #70
